import site_1 from '../../img/1_1554887961-1024x518.jpg';
import site_2 from '../../img/8_1554887948-1024x518.jpg';
import site_3 from '../../img/34_1554887966-1024x518.jpg';
import site_4 from '../../img/hubblesite.png';
import site_5 from '../../img/stellarium.png';

export const rrespons =[
    {h1:'1.If The Moon Were Only 1 Pixel',img:site_1,p: 'Most people are absolutely not standing by how big the cosmos is. Its hardly huge. The site If The Moon Were Only 1 Pixel clearly shows the true size of the solar system. The basis of the scale of the diameter of the servant of the moon - here it corresponds to 1 pixel.Click on the button in the upper right corner of the screen and the solar system will begin to switch in front of you at the speed of light. On a space scale, this is very slow. To Mars at this speed you have to fly more than 12 minutes.',href:'https://joshworth.com/dev/pixelspace/pixelspace_solarsystem.html'},
    {h1: '2.Solar System Exploration',img:site_2,p:'A special NASA page dedicated to all the planets and satellites in the Solar System.Heavenly bodies are beautifully animated,so you can just admire them.But in addition to purely aesthetic enjoyment,the service also provides scientific information about the characteristics of planets,and images of celestial bodies taken by various spacecraft.',href:'https://solarsystem.nasa.gov/'},
    {h1:'3.UFO Hunters',img:site_3,p:'According to UFO Hunters,the number of UFO sightings totals 167 thousand cases.Visit this site to study any of them and read the eyewitness accounts.Here you can also leave your experience of admiring incomprehensible objects in the sky.There are many similar resources,but this one looks better than most.',href:'https://www.ufo-hunters.com/'},
    {h1:'4.HubbleSite',img:site_4,p:'In 1990, the space shuttle Discovery released the Hubble Space Telescope into space. It provides images from deep space, revealing incredible properties about space and time.On HubbleSite, you can stay updated on the latest Hubble news as it discovers black holes, dying stars, galaxies, and more. You can even view astounding images and videos of these discoveries, which truly make you appreciate the scale and wonder of space.Not only that, but you can see what the Hubble is looking at in real time.',href:'https://hubblesite.org/'},
    {h1:'5.Stellarium ',img:site_5,p:'Stellarium Web is a planetarium in your browser. Click and drag your mouse to move your position and explore the stars and planets in the sky. Select one to find out more about it, like its name, magnitude, distance, and visibility.Click the date and time in the bottom-right and you can change the sky to whenever you wish; so you can see how the view changes at moonlight, daylight, twilight, and so on.Theres even a handy observation logbook, where you can record your observations to look back and reminisce or share with friends.',href:'https://stellarium-web.org/'}
]